language: rust

rust:
  - 1.31.1
  - stable
  - beta
  - nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=build_script_build=debug

install:
  - rustup component add rustfmt-preview

script:
  - pwd
  - ls -la
  - cargo test -vv --all
  - cargo build -vv --all --examples
  - cargo test -vv --features openssl --all
  - cargo build -vv --features openssl --all --examples
  - cargo test -vv --no-default-features --features openssl --all
  - cargo build -vv --no-default-features --features openssl --all --examples
